"Boot with standard options"  "quiet nowatchdog splash rw rootflags=subvol=/@ root=UUID=99162e9c-dae3-4e8d-b7f0-686dde6c102e resume=UUID=99162e9c-dae3-4e8d-b7f0-686dde6c102e resume_offset=40641792"
"Boot to single-user mode"    "quiet nowatchdog splash rw rootflags=subvol=/@ root=UUID=99162e9c-dae3-4e8d-b7f0-686dde6c102e single"
"Boot with minimal options"   "ro root=UUID=99162e9c-dae3-4e8d-b7f0-686dde6c102e"
